POST http://localhost:3000/register
Content-Type: application/json

{
    "email" : "knmnddccdcl@gmail.com",
    "username" : "mdddddkkkdcddkjA45_",
    "password" : "Asddeeef999!"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "username" : "mkkkdcddkjA45_",
    "password" : "Asddeeef999!"
}

###
GET http://localhost:3000/seeinfo
Content-Type: application/json