POST http://localhost:3000/register
Content-Type: application/json

{
    "email" : "mahdiedddddh2@gmail.com",
    "username" : "mahdiehh1",
    "password" : "M@hdieh2"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "username" : "mahdieh2",
    "password" : "M@hdieh2"
}

###
# GET http://localhost:3000/seeinfo
# Content-Type: application/json